replicaCount: 1

image:
  repository: saniyar-dev/arvancloud-challenge-app:1.0
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: arvancloud-challenge-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
